# Generated by Django 4.0.4 on 2023-04-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intra_username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
